import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar/NavBar";
import { UserProvider } from '@/context/UserContext';  // Import UserProvider
import Footer from "@/Components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QuilQuest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider> 
          <NavBar/>
          {children}
          {/* <Footer/> */}
        </UserProvider>
      </body>
    </html>
  );
}